# Generated by Django 5.0.6 on 2024-07-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "Select 1;",
            reverse_sql="Select 1;"
        )
    ]
