# Generated by Django 5.0.6 on 2024-07-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floorid', models.AutoField(primary_key=True, serialize=False)),
                ('floorname', models.CharField(max_length=255)),
                ('floordesc', models.CharField(blank=True, max_length=1000, null=True)),
                ('manufacturer', models.CharField(max_length=255)),
                ('onsale', models.BooleanField(blank=True, null=True)),
                ('price', models.TextField()),
                ('inventory', models.IntegerField()),
                ('floortype', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'floor',
                'managed': False,
            },
        ),
    ]
